### PR TITLE
Initial support for Windows capture with Aperture.CLI

### PR DESCRIPTION
**Pull request by sanlyx**
There's still work to do (i.e. audio support, bug fixes, performance improvements) but I think it's a good starting point.
One minor catch is that the current build commands (see package.json) can not be used for cross-platform compatibility, so I added `build-win` and renamed `build` to `build-macos`

### CODE REVIEW

**Comment by albinekb** [comment]
This is cool! I will try this when I get time.

**Comment by wiltonpolesca** [comment]
Hi guys, I'm new here and want to try to help on this project, but, unfortunately, I don't know where to start. There is a tutorial when can I learn about how get the repository, create a pull request and with the rules that need to be respected in the code? 

thanks!

**Comment by skllcrn** [comment]
Hey @wiltonpolesca! Awesome that you want to contribute, I'll see if I can help you get started. I'll go by the presumption that you're already a little familiar working with `git` as well the terms and tools in use.

A good place to start is to check out the repository [readme](https://github.com/wulkano/aperture/blob/master/readme.md), once you've done that you'll want to [clone](https://help.github.com/articles/cloning-a-repository/) it. 

Make sure you're on macOS 10.12 or later and that you have the necessary [dependencies](https://github.com/wulkano/aperture/blob/master/package.json). To do that you're going to need [Node.js](https://www.npmjs.com/get-npm), which includes `npm`. 

Once you've doen that you can `cd` into the directory your cloned the repo to, the easiest way to do that is to open a Terminal window (check out Hyper from our friends at Zeit) and type `cd` before dragging and dropping the folder your cloned onto the command line. Press enter and you should be in the correct directory. 

Now that you're in the `aperture` directory you can run `npm i` which will check the `package.json` I mentioned above and download any missing dependencies for you. Once it's done you can start Apertue by running `npm start`. 

When it comes to rules or guidelines for the code and Aperture itself; it's all about performance and quality. You'll also notice that we use the `xo` linter, which enforces a consistent code style.

**Comment by skllcrn** [comment]
This is a fantastic first contribution @sanlyx, great to have you around! You might also want to check out the new [Window 10 Screen Capture API](https://github.com/wulkano/kap/issues/456).

All this being said, I suggest you move this to your own fork once you're ready. See my message in #46: 

> We've thought a lot about this and have decided to focus our efforts on macOS. That means that we will not officially support or maintain [Aperture](https://github.com/wulkano/aperture) or [Kap](https://github.com/wulkano/kap) on other platforms. 

>This is free and open-source side project for us which we do to learn and *have fun*, the fact of the matter is that we're not currently motivated to maintain these projects on other platforms. That might change in the future, but for now we're letting the community lead. We encourage a fork of Aperture to support other platforms, we'd even encourage you to use the Aperture name, as long as as you develop it to maintain API parity and share our focus on performance and quality.

**Pull request closed without merging**
